name: Go

on:
  push:
    branches: [ pulse ]
  pull_request:
    branches: [ pulse ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: make all

    - name: Test
      run: make test

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ^1.22

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          args: --timeout=5m