name: Go

on:
  push:
    branches: [ pulse ]
  pull_request:
    branches: [ pulse ]

# workflow name
name: Generate release-artifacts

# on events
on:
  release:
    types: 
        - created

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: 'cortextool'
            name: 'cortextool'
            compress: 'false'
            dest: 'dist'